apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fullnameOverride }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  minReadySeconds: {{ .Values.minReadySeconds | default 45 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge | default "25%" }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable | default "25%" }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullnameOverride }}
        {{- with .Values.templateLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.fullnameOverride }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret | default "regcred" }}
      containers:
      - name: {{ .Values.fullnameOverride }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | default "448Mi" | quote }}
            cpu: {{ .Values.resources.requests.cpu | default "250m" | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | default "2000Mi" | quote }}
            cpu: {{ .Values.resources.limits.cpu | default "1000m" | quote }}
        ports:
        - name: liveness-port
          containerPort: {{ .Values.containerPort | default 8090 }}
        - name: readiness-port
          containerPort: {{ .Values.containerPort | default 8090 }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path | default "/" }}
            port: readiness-port
          failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 5 }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 60 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path | default "/" }}
            port: liveness-port
          failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 5 }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 60 }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- end }}
        {{- end }}
        volumeMounts:
        {{- with .Values.volumeMounts }}
        {{ toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      {{- with .Values.volumes }}
      {{ toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
