apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.fullnameOverride }}
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "configmaps", "endpoints"]
    verbs: ["get", "watch", "list"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.fullnameOverride }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fullnameOverride }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.fullnameOverride }}
  apiGroup: rbac.authorization.k8s.io
